### ISSUE TITLE
FormData missing 8 out of 9 methods

### ISSUE THREAD

**Issue by tbenbrahim** [google/elemental2#4]
`FormData` has 9 methods: https://developer.mozilla.org/en-US/docs/Web/API/FormData

only `append` is implemented in elemental2

**Comment by tbroyer** [comment]
`FormData` is not defined in this repository (https://github.com/google/elemental2/search?q=FormData&type=Code&utf8=%E2%9C%93) so I think the issue should be created on the Closure Compiler repository, where it's defined (with only the `append` method): https://github.com/google/closure-compiler/blob/839656d772ae2dd5bbcc448442105422cb548ca1/externs/browser/w3c_xml.js#L435-L452

**Comment by tbroyer** [comment]
…and it might be due to the fact that neither Safari nor Edge (or Internet Explorer) implement the other methods, according to https://developer.mozilla.org/en-US/docs/Web/API/FormData#Browser_compatibility (i.e. might actually be on-purpose and not just an oversight)

**Comment by jDramaix** [comment]
**Contribution is welcome here.**

Now it's implemented in Safari 11, I'm sure closure-compiler authors will accept a patch for adding these methods to `FormData` type.

This can be fixed by adding the missing methods to [google/closure-compiler/blob/master/externs/browser/w3c_xml.js](https://github.com/google/closure-compiler/blob/master/externs/browser/w3c_xml.js#L443)

**Comment by realityforge** [comment]
@jDramaix Closure externs have been updated and this issue can be closed.

See https://github.com/google/closure-compiler/blob/master/externs/browser/w3c_xml.js#L446-L494

**Comment by jDramaix** [comment]
Thanks!!
