### ISSUE TITLE
activeElement is missing from Document

### ISSUE THREAD

**Issue by vegegoku** [google/elemental2#40]
Elemental2 version : 1.0.0-RC1
The document object provide by DomGloabl does not have the activeElement property
as a workaround i extended the HTMLDocument type and added the property and it worked out
```
@JsType(isNative = true, namespace = JsPackage.GLOBAL)
public class MyDocument extends HTMLDocument {
    public Element activeElement;
}
```
checking this out on MDN it says it is supported by most of modern browsers.

https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/activeElement

**Comment by niloc132** [comment]
Suggest changing the title and topic of this - @jDramaix, according to MatrixFrog over at https://github.com/google/closure-compiler/pull/2865, elemental2 should perhaps be pulling in more of the `*_dom.js` files (specifically ie_dom.js), since it appears that `activeElement` already exists and should not be moved (though it's type is too specific and must be fixed still).

> It being in ie_dom.js doesn't mean it's IE only, it just means that most likely it was in IE first so that's where it got added. We should perhaps move it to w3c_dom1.js or something, but since most projects just use all the default externs it doesn't actually matter too much which file it's in.

It isn't entirely clear to me which direction this should go, but at least other closure-compatible projects seem to prefer adding more extern files. 

Alternatives that may be worth considering:
 * Expect that upstream closure-compiler change their extern organization, so that elemental2 need only list the `w3c` files, nothing browser-specific
 * Don't worry about missed browser features, require downstream applications to make their own workarounds for all
 * Add all now-standardized properties from `*_dom.js` etc files to the various `.diff`s in elemental2

---

This remains a difficult topic for us non-Googlers to approach, we're hoping for your guidance here in coordinating between different Google projects (even if non-official).

**Comment by jDramaix** [comment]
The extern files need a lot of clean-up. In this case I think we should move activeElement to w3c_dom1.js (closure guys are ok with that) but unfortunately sometimes that kind of move can break complex js applications.

So my recommendation is:
- try to clean up extern file first: move missing api in w3c_xyz.js if the api is standardized
- If anyhow, the change is not possible, change the corresponding diff file in order to patch our version of w3c_xyz.js 

I'll do that for activeElement

**Comment by niloc132** [comment]
My update on this: ShadowRoot.java already has this, and Document already has this in the closure externs, and was updated to be correct, but still unusable from elemental2 (it now has `@type {!Element}` on it, but in ie_dom.js, which is sufficient for closure-compiler to see it on any project given to it, but elemental2 doesn't look at other browser-suffixed projects.

Any update on your end? I'm not seeing a single change rearranging any externs which were originally placed in a browser specific extern due to them providing the initial implementation.

**Comment by realityforge** [comment]
See google/closure-compiler#3393 which will fix this once merged

**Comment by realityforge** [comment]
This has been fixed upstream so this issue can be closed

**Comment by jDramaix** [comment]
Thanks
