### ISSUE TITLE
ServiceWorkerContainer.onmessage missing

### ISSUE THREAD

**Issue by BenDol** [google/elemental2#53]
The ServiceWorkerContainer.onmessage property is missing: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/onmessage

**Comment by gkdn** [comment]
Seems like w3c_serviceworker.js is missing it. If you like to provide a patch, pls see the instructions here: https://github.com/google/elemental2/blob/master/CONTRIBUTING.md#contributing-a-patch

**Comment by jDramaix** [comment]
**Contribution is welcome here.**

 w3c_serviceworker.js is included in elemental2-dom but the method `onmessage` is missing on `ServiceWorkerContainer`.

This can be easily fixed by adding the method `onmessage` on `ServiceWorkerContainer` prototype in [w3c_serviceworker.js](https://github.com/google/closure-compiler/blob/master/externs/browser/w3c_serviceworker.js#L271)

**Comment by realityforge** [comment]
PR submitted as google/closure-compiler#3329

**Comment by realityforge** [comment]
This has been fixed upstream and will appear in the next release of elemental2 ... so the issue can probably be closed for now

**Comment by jDramaix** [comment]
I confirm!
