### ISSUE TITLE
Navigator missing getMedia, getUserMedia, mozGetUserMedia, msGetUserMedia

### ISSUE THREAD

**Issue by BenDol** [google/elemental2#55]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia

**Comment by jDramaix** [comment]
This need to be fixed in [closure-compiler repository](https://github.com/google/closure-compiler). 
The functions have to be added to [google/closure-compiler/blob/master/externs/browser/w3c_rtc.js](https://github.com/google/closure-compiler/blob/master/externs/browser/w3c_rtc.js#L1119)

**Comment by softweaver** [comment]
Navigator should be missing getMedia, getUserMedia, mozGetUserMedia, msGetUserMedia because they have been deprecated.

See:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia

Modern usage is:
navigator.mediaDevices.getUserMedia()

Verified today that elemental2 1.0.0-RC1 properly contains:

in elemental2.dom.Navigator:
public MediaDevices mediaDevices;

in elemental2.dom.MediaDevices:
Promise<MediaStream> getUserMedia(MediaStreamConstraints constraints);

Ergo, this issue can be closed.

**Comment by jDramaix** [comment]
Thanks!
