### ISSUE TITLE
Document.window.devicePixelRatio is missing from DomGlobal.window, could we have it ?

### ISSUE THREAD

**Issue by treblereel** [google/elemental2#59]
the devicePixelRatio method is missing from DomGlobal.window. It would be very nice to add it.

**Comment by niloc132** [comment]
Another option would be to add it to `dom_missing_api.js`, like Location and Selection and others currently do. The `devicePixelRatio` property is defined in `webkit_dom.js` only, but it works in other browsers (according to https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio, is available in IE11 and above).

Or, as was suggested in a closure-compiler, modify the build rule for elemental2-dom to also include all `*_dom.js` files, instead of only the "standardized" ones (since many of the browser-specific ones have actually been standardized, but closure-compiler's policy is to not move the file to `w3c_dom.js` at that time).

**Comment by jDramaix** [comment]
Will be fixed when #88 is fixed
