### ISSUE TITLE
MediaError static fields uses Doubles and does not have defined constants

### ISSUE THREAD

**Issue by mdproctor** [google/elemental2#71]
We cannot switch on MediaError as it has doubles for the static fields, instead of ints.

Also the actual values are not assigned as constants, which also means it cannot be used in a switch statement.

https://developer.mozilla.org/en-US/docs/Web/API/MediaError

**Comment by jDramaix** [comment]
**Contribution is welcome here.**

This can be easily fixed by 
 - modifying [dom/integer_entities.txt](https://github.com/google/elemental2/blob/master/java/elemental2/dom/integer_entities.txt) for listing these members as integer entities.
 - Mark these members as constant in [google/closure-compiler/blob/master/externs/browser/html5.js](https://github.com/google/closure-compiler/blob/master/externs/browser/html5.js#L2385)

**Comment by realityforge** [comment]
@jDramaix This issue is now completed and can be closed

**Comment by jDramaix** [comment]
Thanks!
